# Generated by Django 3.1.3 on 2020-11-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Note',
            new_name='User',
        ),
    ]
