# Generated by Django 3.1.3 on 2020-11-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
                ('note_field', models.TextField(max_length=1000, verbose_name='My field label')),
            ],
        ),
    ]
