# Generated by Django 3.1.3 on 2020-11-16 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='added_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
