# Generated by Django 3.1.3 on 2020-12-09 21:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20201116_0207'),
    ]

    operations = [
        migrations.CreateModel(
            name='sub_Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_text', models.CharField(max_length=100)),
                ('added_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('note_field', models.TextField(max_length=1000, verbose_name='My field label')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
            ],
        ),
    ]
